[package]
name = "dns_challenge"
version = "0.1.0"
authors = ["The Project Link Developers"]
publish = false

[[bin]]
name = "dnschallenge"
path = "main.rs"

[replace]
"iron:0.3.0" = { path = "../../iron-fork/" }

[dependencies.tls]
path = "../tls"

[dependencies]
clippy = "0.0.63"
