#!/bin/bash

set -ex

CURRENT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_HOME="$CURRENT_PATH/.."
FOXBOX_BINARY="$PROJECT_HOME/target/debug/foxbox"

DEBUG_HOST=${BOX_LOCAL_NAME:-'localhost'}
DEBUG_PORT=${BOX_PORT:-3331}
DEBUG_PROFILE="$HOME/.local/share/foxbox-debug"

# clean up residual profile
rm -rf "${DEBUG_PROFILE}"



# run tests
BOX_PORT=${DEBUG_PORT} "${PROJECT_HOME}/node_modules/.bin/mocha" "${PROJECT_HOME}/test/selenium/*_test.js"

# clean up foxbox process
kill $FOXBOX_PID
