#!/bin/bash

set -ex

CURRENT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_HOME="$CURRENT_PATH/.."
FOXBOX_BINARY="$PROJECT_HOME/target/debug/foxbox"

DEBUG_HOST=${BOX_LOCAL_NAME:-'localhost'}
DEBUG_PORT=${BOX_PORT:-3331}
DEBUG_PROFILE="$HOME/.local/share/foxbox-debug"

# clean up residual profile
rm -rf "${DEBUG_PROFILE}"

# build and launch foxbox daemon
pushd "${PROJECT_HOME}"
cargo build
if [ "$(uname)" == "Darwin" ]; then
    # Do not use hostname flag on Mac since it is only implemented in Linux ATM.
    RUST_BACKTRACE=1 "$FOXBOX_BINARY" --port ${DEBUG_PORT} --disable-tls --profile "${DEBUG_PROFILE}" &
else
    RUST_BACKTRACE=1 "$FOXBOX_BINARY" --local-name ${DEBUG_HOST} --port ${DEBUG_PORT} --disable-tls --profile "${DEBUG_PROFILE}" &
fi
FOXBOX_PID=$!
popd

# run tests
BOX_PORT=${DEBUG_PORT} "${PROJECT_HOME}/node_modules/.bin/mocha" "${PROJECT_HOME}/test/selenium/*_test.js"

# clean up foxbox process
kill $FOXBOX_PID
